web_blog/blog/urls.py
#!/usr/bin/python3
# -*- coding: utf-8 -*- 
# @Time : 2019/7/23 11:43
# @Author : Tan 
# @Email : 1531391246@qq.com
# @File : urls.py
# @Software: PyCharm


from django.urls import path
from blog import views

app_name = 'post'
urlpatterns = [
    path(r'', views.IndexView.as_view(), name='post-list'),
    path(r'article/<int:post_id>/', views.PostDetailView.as_view(), name='post-detail'),
    path(r'category/<int:category_id>/', views.CategoryView.as_view(), name='category-list'),


]

web_blog/blog_system/urls.py
#!/usr/bin/python3
# -*- coding: utf-8 -*- 
# @Time : 2019/7/25 18:55
# @Author : Tan 
# @Email : 1531391246@qq.com
# @File : urls.py
# @Software: PyCharm


from blog_system.views import Index
from django.urls import path


app_name = 'blog_system'
urlpatterns = [
    path(r'<str:pro_category_id>', Index.as_view(), name='index'),
]

web_blog/blog_system/models.py
from django.db import models


class ProjectCategory(models.Model):
    STATUS_NORMAL = 1
    STATUS_DELETE = 0
    STATUS_ITEMS = (
        (STATUS_NORMAL, '正常'),
        (STATUS_DELETE, '删除'),
    )

    name = models.CharField(max_length=50, verbose_name="名称")
    status = models.PositiveIntegerField(default=STATUS_NORMAL, choices=STATUS_ITEMS, verbose_name="状态")
    created_time = models.DateTimeField(auto_now_add=True, verbose_name="创建时间")

    class Meta:
        verbose_name = verbose_name_plural = "系统分类"

    def __str__(self):
        return self.name

    @classmethod
    def get_pro_category(cls):
        return cls.objects.filter(status=cls.STATUS_NORMAL)

web_blog/user/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class UserInfo(models.Model):
    owner = models.OneToOneField(User, on_delete=models.CASCADE, null=True, verbose_name="账号")
    name = models.CharField(max_length=50, verbose_name="用户名", unique=True)
    nickname = models.CharField(max_length=50, verbose_name="昵称", null=True)
    sex = models.PositiveSmallIntegerField(default=2, choices=((0, '男'), (1, '女'), (2, '未知')), verbose_name="性别",
                                           null=True, blank=True)
    birthday = models.DateField(null=True, verbose_name="生日", blank=True)
    introduction = models.CharField(max_length=254, verbose_name="个人描述", default="该用户很懒，什么也没有留下...", blank=True)
    address = models.CharField(max_length=50, null=True, default="未知", blank=True, verbose_name="地址")

    objects = models.Manager()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = verbose_name_plural = "个人信息"


class EmailVerification(models.Model):
    STATUS_REGISTER = 0
    STATUS_FORGET = 1
    STATUS_ITEM = (
        (STATUS_REGISTER, '邮箱注册'),
        (STATUS_FORGET, '忘记密码'),
    )
    account = models.EmailField(verbose_name="账号")
    status = models.PositiveIntegerField(choices=STATUS_ITEM, verbose_name="状态")
    code = models.CharField(max_length=64, verbose_name="验证码")

    objects = models.Manager()

    class Meta:
        verbose_name = verbose_name_plural = "邮箱验证"

web_blog/blog_system/views.py
from django.shortcuts import get_object_or_404
from django.utils.decorators import method_decorator
from django.views.generic import ListView
from django.views.decorators.cache import cache_page
from blog.models import Post
from blog_system.models import ProjectCategory


# Create your views here.


class IndexViewMixin:
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        pro_category_id = self.kwargs.get('pro_category_id', -1)
        if pro_category_id == -1:
            pro_category = get_object_or_404(ProjectCategory, name="推荐")
        else:
            pro_category = get_object_or_404(ProjectCategory, id=pro_category_id)
        context.update({
            'pro_category_list': ProjectCategory.get_pro_category(),
            'pro_category': pro_category
        })
        return context


class Index(IndexViewMixin, ListView):

    def get_queryset(self):
        pro_category_id = self.kwargs.get('pro_category_id', -1)
        if pro_category_id == -1:
            queryset = Post.objects.all().order_by('-created_time')[:100]
        else:
            queryset = Post.objects.filter(pro_category_id=pro_category_id)[:100]
        return queryset

    @method_decorator(cache_page(60 * 60 * 24))
    def get(self, request, *args, **kwargs):
        return super(Index, self).get(request, *args, **kwargs)

    paginate_by = 10
    template_name = 'blog_system/index.html'
    context_object_name = 'post_list'

web_blog/extra_apps/xadmin2-2.0.1/xadmin/views/base.py
import copy
import functools
import datetime
import decimal
from functools import update_wrapper
from inspect import getfullargspec

from django import forms
from django.apps import apps
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_permission_codename
from django.core.exceptions import ValidationError
from django.core.serializers.json import DjangoJSONEncoder
from django.urls.base import reverse
from django.http import HttpResponse
from django.template import Context, Template
from django.template.response import TemplateResponse
from django.utils import six
from django.utils.decorators import method_decorator, classonlymethod
from django.utils.encoding import force_text, smart_text, smart_str
from django.utils.functional import Promise
from django.utils.http import urlencode
from django.utils.itercompat import is_iterable
from django.utils.safestring import mark_safe
from django.utils.text import capfirst
from django.utils.translation import ugettext as _
from django.views.decorators.csrf import csrf_protect
from django.views.generic import View
from collections import OrderedDict
from xadmin.util import static, json, vendor, sortkeypicker

from xadmin.models import Log

csrf_protect_m = method_decorator(csrf_protect)


class IncorrectPluginArg(Exception):
    pass


def get_content_type_for_model(obj):
    from django.contrib.contenttypes.models import ContentType
    return ContentType.objects.get_for_model(obj, for_concrete_model=False)


def filter_chain(filters, token, func, *args, **kwargs):
    if token == -1:
        return func()
    else:
        def _inner_method():
            fm = filters[token]
            fargs = getfullargspec(fm)[0]
            if len(fargs) == 1:
                # Only self arg
                result = func()
                if result is None:
                    return fm()
                else:
                    raise IncorrectPluginArg(u'Plugin filter method need a arg to receive parent method result.')
            else:
                return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
        return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)


def filter_hook(func):
    tag = func.__name__
    func.__doc__ = "``filter_hook``\n\n" + (func.__doc__ or "")

    @functools.wraps(func)
    def method(self, *args, **kwargs):

        def _inner_method():
            return func(self, *args, **kwargs)

        if self.plugins:
            filters = [(getattr(getattr(p, tag), 'priority', 10), getattr(p, tag))
                       for p in self.plugins if callable(getattr(p, tag, None))]
            filters = [f for p, f in sorted(filters, key=lambda x:x[0])]
            return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
        else:
            return _inner_method()
    return method


def inclusion_tag(file_name, context_class=Context, takes_context=False):
    def wrap(func):
        @functools.wraps(func)
        def method(self, context, nodes, *arg, **kwargs):
            _dict = func(self, context, nodes, *arg, **kwargs)
            from django.template.loader import get_template, select_template
            cls_str = str if six.PY3 else basestring
            if isinstance(file_name, Template):
                t = file_name
            elif not isinstance(file_name, cls_str) and is_iterable(file_name):
                t = select_template(file_name)
            else:
                t = get_template(file_name)

            _dict['autoescape'] = context.autoescape
            _dict['use_l10n'] = context.use_l10n
            _dict['use_tz'] = context.use_tz
            _dict['admin_view'] = context['admin_view']

            csrf_token = context.get('csrf_token', None)
            if csrf_token is not None:
                _dict['csrf_token'] = csrf_token
            nodes.append(t.render(_dict))

        return method
    return wrap


class JSONEncoder(DjangoJSONEncoder):

    def default(self, o):
        if isinstance(o, datetime.datetime):
            return o.strftime('%Y-%m-%d %H:%M:%S')
        elif isinstance(o, datetime.date):
            return o.strftime('%Y-%m-%d')
        elif isinstance(o, decimal.Decimal):
            return str(o)
        elif isinstance(o, Promise):
            return force_text(o)
        else:
            try:
                return super(JSONEncoder, self).default(o)
            except Exception:
                return smart_text(o)


class BaseAdminObject(object):

    def get_view(self, view_class, option_class=None, *args, **kwargs):
        opts = kwargs.pop('opts', {})
        return self.admin_site.get_view_class(view_class, option_class, **opts)(self.request, *args, **kwargs)

    def get_model_view(self, view_class, model, *args, **kwargs):
        return self.get_view(view_class, self.admin_site._registry.get(model), *args, **kwargs)

    def get_admin_url(self, name, *args, **kwargs):
        return reverse('%s:%s' % (self.admin_site.app_name, name), args=args, kwargs=kwargs)

    def get_model_url(self, model, name, *args, **kwargs):
        return reverse(
            '%s:%s_%s_%s' % (self.admin_site.app_name, model._meta.app_label,
                             model._meta.model_name, name),
            args=args, kwargs=kwargs, current_app=self.admin_site.name)

    def get_model_perm(self, model, name):
        return '%s.%s_%s' % (model._meta.app_label, name, model._meta.model_name)

    def has_model_perm(self, model, name, user=None):
        user = user or self.user
        return user.has_perm(self.get_model_perm(model, name)) or (name == 'view' and self.has_model_perm(model, 'change', user))

    def get_query_string(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return '?%s' % urlencode(p)

    def get_form_params(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return mark_safe(''.join(
            '<input type="hidden" name="%s" value="%s"/>' % (k, v) for k, v in p.items() if v))

    def render_response(self, content, response_type='json'):
        if response_type == 'json':
            response = HttpResponse(content_type="application/json; charset=UTF-8")
            response.write(
                json.dumps(content, cls=JSONEncoder, ensure_ascii=False))
            return response
        return HttpResponse(content)

    def template_response(self, template, context):
        return TemplateResponse(self.request, template, context)

    def message_user(self, message, level='info'):
        """
        Send a message to the user. The default implementation
        posts a message using the django.contrib.messages backend.
        """
        if hasattr(messages, level) and callable(getattr(messages, level)):
            getattr(messages, level)(self.request, message)

    def static(self, path):
        return static(path)

    def vendor(self, *tags):
        return vendor(*tags)

    def log(self, flag, message, obj=None):
        log = Log(
            user=self.user,
            ip_addr=self.request.META['REMOTE_ADDR'],
            action_flag=flag,
            message=message
        )
        if obj:
            log.content_type = get_content_type_for_model(obj)
            log.object_id = obj.pk
            log.object_repr = force_text(obj)
        log.save()


class BaseAdminPlugin(BaseAdminObject):

    def __init__(self, admin_view):
        self.admin_view = admin_view
        self.admin_site = admin_view.admin_site

        if hasattr(admin_view, 'model'):
            self.model = admin_view.model
            self.opts = admin_view.model._meta

    def init_request(self, *args, **kwargs):
        pass


class BaseAdminView(BaseAdminObject, View):
    """ Base Admin view, support some comm attrs."""

    base_template = 'xadmin/base.html'
    need_site_permission = True

    def __init__(self, request, *args, **kwargs):
        self.request = request
        self.request_method = request.method.lower()
        self.user = request.user

        self.base_plugins = [p(self) for p in getattr(self,
                                                      "plugin_classes", [])]

        self.args = args
        self.kwargs = kwargs
        self.init_plugin(*args, **kwargs)
        self.init_request(*args, **kwargs)

    @classonlymethod
    def as_view(cls):
        def view(request, *args, **kwargs):
            self = cls(request, *args, **kwargs)

            if hasattr(self, 'get') and not hasattr(self, 'head'):
                self.head = self.get

            if self.request_method in self.http_method_names:
                handler = getattr(
                    self, self.request_method, self.http_method_not_allowed)
            else:

web_blog/themes/default/templates/blog_system/user_info/base.html
{% extends 'base_page/base.html' %}
{% load static %}
{% block extra_title %}-个人中心-PDBG{% endblock %}
{% block sidebars %}
    <!-- 侧边栏 -->
    <div class="col-md-2 area">
        <ul class="list-group">
            <li class="list-group-item"><a href="#">个人资料</a></li>
            <li class="list-group-item"><a href="#">我的收藏</a></li>
            <li class="list-group-item"><a href="#">我的关注</a></li>
            <li class="list-group-item"><a href="#">我的粉丝</a></li>
            <li class="list-group-item"><a href="#">我的博客</a></li>
            <li class="list-group-item"><a href="#">我的下载</a></li>
            <li class="list-group-item"><a href="#">我的论坛</a></li>
        </ul>
    </div>
{% endblock %}

web_blog/themes/default/templates/blog_system/user_info/personal_info.html
{% extends 'blog_system/user_info/base.html' %}
{% load static %}
{% block title %}个人资料{% endblock %}
{% block extra_head %}
        <link rel="stylesheet" href="{% static 'default/css/user_info.css' %}">
{% endblock %}
{% block main %}
    <div class="col-md-9 area">
        <ul class="list-group">
            <li class="list-group-item">
                <h3 class="info-title">个人资料</h3>
                <div class="row">
                    <div class="col-md-2">
                        <img src="{% static 'imgs/SC01C14.jpg' %}" alt="" style="height: 100px;width: 100px;margin-top: 16px" class="img-circle">
                    </div>
                    <div class="col-md-9 area">
                        <div class="right-info">
                            <div class="id-card">
                                <span class="id-name">ID：{{ user_info.name }}</span>
                                <a href="{% url 'post:post-list' user_info.name %}" class="user-home text-right">个人主页</a>
                            </div>
                        </div>
                        <div class="pdbg-info">
                            <span class="span-info">关注 X</span>
                            <span class="span-info">粉丝 X</span>
                        </div>
                        <div class="line"></div>
                        <div class="nick-name">
                            <span class="nickname">昵称：{{ user_info.nickname }}</span>
                            <span class="mod" id="edit-button">修改资料</span>
                        </div>
                        <ul class="self">
                            <li class="common sex">性别：{{ user_info.get_sex_display }}</li>
                            <li class="common birthday">生日：{{ user_info.birthday }}</li>
                            <li class="common address">地址：{{ user_info.address }}</li>
                            <li class="common introduction">简介：{{ user_info.introduction }}</li>
                        </ul>
                    </div>
                </div>
            </li>
        </ul>
    </div>
    <div class="dialog hidden" id="edit-form">
        <div class="dialog-cont">
            <div class="box">
                <h3 class="title">修改资料</h3>
                <span class="close">×</span>
            </div>
            <form action="{% url 'edit_info' %}" method="post" id="fm">
            {% for field in info_form %}
                <p class="nick word">
                        <span class="nc">{{ field.label }}：</span>
                        {{ field }}
                </p>
            {% endfor %}
            {% csrf_token %}
            <div class="btn-group-list">
                <input type="button" class="cancel" value="取消">
                <input type="button" class="confirm" value="确定">
            </div>
            </form>
        </div>
    </div>
{% endblock %}
{% block extra_script %}
    <script src="{% static 'default/js/user_info.js' %}" type="text/javascript"></script>
{% endblock %}