web_blog/blog/urls.py
#!/usr/bin/python3
# -*- coding: utf-8 -*- 
# @Time : 2019/7/23 11:43
# @Author : Tan 
# @Email : 1531391246@qq.com
# @File : urls.py
# @Software: PyCharm


from django.urls import path
from blog import views

app_name = 'post'
urlpatterns = [
    path(r'', views.IndexView.as_view(), name='post-list'),
    path(r'article/<int:post_id>/', views.PostDetailView.as_view(), name='post-detail'),
    path(r'category/<int:category_id>/', views.CategoryView.as_view(), name='category-list'),


]

web_blog/blog/views.py
from datetime import date
from django.core.cache import cache
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404
from django.utils.decorators import method_decorator
from django.views.generic import ListView, DetailView
from django.views.decorators.cache import cache_page
from django.db.models import F
from .models import Post, Category
from config.models import SideBar
from comment.models import Snap

# Create your views here.


class CommonViewMixin:
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        auth = self.kwargs.get('auth')
        auth_obj = get_object_or_404(User, userinfo__name=auth)
        context.update({
            'sidebars': SideBar.get_all(auth_obj),
            'auth': auth
        })
        return context


class IndexView(CommonViewMixin, ListView):
    def get_queryset(self):
        auth = self.kwargs.get('auth')
        auth_obj = get_object_or_404(User, userinfo__name=auth)
        queryset = Post.latest_posts(auth_obj)
        return queryset

    @method_decorator(cache_page(60 * 1))
    def get(self, request, *args, **kwargs):
        return super(IndexView, self).get(request, *args, **kwargs)

    paginate_by = 10
    context_object_name = 'post_list'
    template_name = 'blog/list.html'


class CategoryView(IndexView):
    """根据分类查看文章"""
    def get_context_data(self, **kwargs):
        context = super(CategoryView, self).get_context_data(**kwargs)
        category_id = self.kwargs.get('category_id')
        category = get_object_or_404(Category, id=category_id)
        context.update({
            'category': category,
        })
        return context

    @method_decorator(cache_page(60 * 1))
    def get(self, request, *args, **kwargs):
        return super(CategoryView, self).get(request, *args, **kwargs)

    def get_queryset(self):
        queryset = super(CategoryView, self).get_queryset()
        category_id = self.kwargs.get('category_id')
        return queryset.filter(category_id=category_id)


class PostDetailView(CommonViewMixin, DetailView):
    """博客详情页面"""
    def get_queryset(self):
        auth = self.kwargs.get('auth')
        auth_obj = get_object_or_404(User, userinfo__name=auth)
        queryset = Post.latest_posts(auth_obj)
        return queryset

    def get_context_data(self, **kwargs):
        context = super(PostDetailView, self).get_context_data(**kwargs)
        post_id = self.kwargs.get('post_id')
        if not self.request.user.is_authenticated:
            snap = False
        else:
            snap = Snap.objects.filter(post_id=post_id, user=self.request.user)
        context.update({
            'snap': snap
        })
        return context

    template_name = 'blog/detail.html'
    context_object_name = 'post'
    pk_url_kwarg = 'post_id'

    @method_decorator(cache_page(60 * 1))
    def get(self, request, *args, **kwargs):
        response = super().get(request, *args, **kwargs)
        self.handle_visited()
        return response

    def handle_visited(self):
        increase_uv = False
        uid = self.request.uid
        uv_key = 'uv:%s:%s:%s' % (uid, str(date.today()), self.request.path)
        if not cache.get(uv_key):
            increase_uv = True
            cache.set(uv_key, 1, 60*60*24)
        if increase_uv:
            Post.objects.filter(pk=self.object.id).update(uv=F('uv')+1)

web_blog/extra_apps/xadmin2-2.0.1/xadmin/views/base.py
import copy
import functools
import datetime
import decimal
from functools import update_wrapper
from inspect import getfullargspec

from django import forms
from django.apps import apps
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_permission_codename
from django.core.exceptions import ValidationError
from django.core.serializers.json import DjangoJSONEncoder
from django.urls.base import reverse
from django.http import HttpResponse
from django.template import Context, Template
from django.template.response import TemplateResponse
from django.utils import six
from django.utils.decorators import method_decorator, classonlymethod
from django.utils.encoding import force_text, smart_text, smart_str
from django.utils.functional import Promise
from django.utils.http import urlencode
from django.utils.itercompat import is_iterable
from django.utils.safestring import mark_safe
from django.utils.text import capfirst
from django.utils.translation import ugettext as _
from django.views.decorators.csrf import csrf_protect
from django.views.generic import View
from collections import OrderedDict
from xadmin.util import static, json, vendor, sortkeypicker

from xadmin.models import Log

csrf_protect_m = method_decorator(csrf_protect)


class IncorrectPluginArg(Exception):
    pass


def get_content_type_for_model(obj):
    from django.contrib.contenttypes.models import ContentType
    return ContentType.objects.get_for_model(obj, for_concrete_model=False)


def filter_chain(filters, token, func, *args, **kwargs):
    if token == -1:
        return func()
    else:
        def _inner_method():
            fm = filters[token]
            fargs = getfullargspec(fm)[0]
            if len(fargs) == 1:
                # Only self arg
                result = func()
                if result is None:
                    return fm()
                else:
                    raise IncorrectPluginArg(u'Plugin filter method need a arg to receive parent method result.')
            else:
                return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
        return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)


def filter_hook(func):
    tag = func.__name__
    func.__doc__ = "``filter_hook``\n\n" + (func.__doc__ or "")

    @functools.wraps(func)
    def method(self, *args, **kwargs):

        def _inner_method():
            return func(self, *args, **kwargs)

        if self.plugins:
            filters = [(getattr(getattr(p, tag), 'priority', 10), getattr(p, tag))
                       for p in self.plugins if callable(getattr(p, tag, None))]
            filters = [f for p, f in sorted(filters, key=lambda x:x[0])]
            return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
        else:
            return _inner_method()
    return method


def inclusion_tag(file_name, context_class=Context, takes_context=False):
    def wrap(func):
        @functools.wraps(func)
        def method(self, context, nodes, *arg, **kwargs):
            _dict = func(self, context, nodes, *arg, **kwargs)
            from django.template.loader import get_template, select_template
            cls_str = str if six.PY3 else basestring
            if isinstance(file_name, Template):
                t = file_name
            elif not isinstance(file_name, cls_str) and is_iterable(file_name):
                t = select_template(file_name)
            else:
                t = get_template(file_name)

            _dict['autoescape'] = context.autoescape
            _dict['use_l10n'] = context.use_l10n
            _dict['use_tz'] = context.use_tz
            _dict['admin_view'] = context['admin_view']

            csrf_token = context.get('csrf_token', None)
            if csrf_token is not None:
                _dict['csrf_token'] = csrf_token
            nodes.append(t.render(_dict))

        return method
    return wrap


class JSONEncoder(DjangoJSONEncoder):

    def default(self, o):
        if isinstance(o, datetime.datetime):
            return o.strftime('%Y-%m-%d %H:%M:%S')
        elif isinstance(o, datetime.date):
            return o.strftime('%Y-%m-%d')
        elif isinstance(o, decimal.Decimal):
            return str(o)
        elif isinstance(o, Promise):
            return force_text(o)
        else:
            try:
                return super(JSONEncoder, self).default(o)
            except Exception:
                return smart_text(o)


class BaseAdminObject(object):

    def get_view(self, view_class, option_class=None, *args, **kwargs):
        opts = kwargs.pop('opts', {})
        return self.admin_site.get_view_class(view_class, option_class, **opts)(self.request, *args, **kwargs)

    def get_model_view(self, view_class, model, *args, **kwargs):
        return self.get_view(view_class, self.admin_site._registry.get(model), *args, **kwargs)

    def get_admin_url(self, name, *args, **kwargs):
        return reverse('%s:%s' % (self.admin_site.app_name, name), args=args, kwargs=kwargs)

    def get_model_url(self, model, name, *args, **kwargs):
        return reverse(
            '%s:%s_%s_%s' % (self.admin_site.app_name, model._meta.app_label,
                             model._meta.model_name, name),
            args=args, kwargs=kwargs, current_app=self.admin_site.name)

    def get_model_perm(self, model, name):
        return '%s.%s_%s' % (model._meta.app_label, name, model._meta.model_name)

    def has_model_perm(self, model, name, user=None):
        user = user or self.user
        return user.has_perm(self.get_model_perm(model, name)) or (name == 'view' and self.has_model_perm(model, 'change', user))

    def get_query_string(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return '?%s' % urlencode(p)

    def get_form_params(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return mark_safe(''.join(
            '<input type="hidden" name="%s" value="%s"/>' % (k, v) for k, v in p.items() if v))

    def render_response(self, content, response_type='json'):
        if response_type == 'json':
            response = HttpResponse(content_type="application/json; charset=UTF-8")
            response.write(
                json.dumps(content, cls=JSONEncoder, ensure_ascii=False))
            return response
        return HttpResponse(content)

    def template_response(self, template, context):
        return TemplateResponse(self.request, template, context)

    def message_user(self, message, level='info'):
        """
        Send a message to the user. The default implementation
        posts a message using the django.contrib.messages backend.
        """
        if hasattr(messages, level) and callable(getattr(messages, level)):
            getattr(messages, level)(self.request, message)

    def static(self, path):
        return static(path)

    def vendor(self, *tags):
        return vendor(*tags)

    def log(self, flag, message, obj=None):
        log = Log(
            user=self.user,
            ip_addr=self.request.META['REMOTE_ADDR'],
            action_flag=flag,
            message=message
        )
        if obj:
            log.content_type = get_content_type_for_model(obj)
            log.object_id = obj.pk
            log.object_repr = force_text(obj)
        log.save()


class BaseAdminPlugin(BaseAdminObject):

    def __init__(self, admin_view):
        self.admin_view = admin_view
        self.admin_site = admin_view.admin_site

        if hasattr(admin_view, 'model'):
            self.model = admin_view.model
            self.opts = admin_view.model._meta

    def init_request(self, *args, **kwargs):
        pass


class BaseAdminView(BaseAdminObject, View):
    """ Base Admin view, support some comm attrs."""

    base_template = 'xadmin/base.html'
    need_site_permission = True

    def __init__(self, request, *args, **kwargs):
        self.request = request
        self.request_method = request.method.lower()
        self.user = request.user

        self.base_plugins = [p(self) for p in getattr(self,
                                                      "plugin_classes", [])]

        self.args = args
        self.kwargs = kwargs
        self.init_plugin(*args, **kwargs)
        self.init_request(*args, **kwargs)

    @classonlymethod
    def as_view(cls):
        def view(request, *args, **kwargs):
            self = cls(request, *args, **kwargs)

            if hasattr(self, 'get') and not hasattr(self, 'head'):
                self.head = self.get

            if self.request_method in self.http_method_names:
                handler = getattr(
                    self, self.request_method, self.http_method_not_allowed)
            else:

web_blog/themes/default/templates/blog/base.html
{% extends "base_page/base.html" %}
{% load static %}
{% block extra_title %}-PDBG博客{% endblock %}
{% block extra_head %}
    <link rel="stylesheet" href="{% static 'default/css/blog.css' %}">
{% endblock %}
{% block sidebars %}
    <!-- 侧边栏 -->
    <div class="col-md-3 post-item">
        <ul class="list-group">
            <li class="list-group-item info-block">
                <div class="profile-intro d-flex">
                    <div class="avatar-box">
                        <img src="{% static 'imgs/SC01C14.jpg' %}" alt="" style="height: 48px;width: 48px;margin-top: 16px" class="img-circle" alt="">
                    </div>
                    <div class="auth-name">
                        <p class="p-name">{{ auth }}</p>
                    </div>
                </div>
                <div class="data-info">
                    <dl class="text-center">
                        <dt><a href="#" class="a-color">原创</a></dt>
                        <dd><span class="count">126</span></dd>
                    </dl>
                    <dl class="text-center">
                        <dt><a href="#" class="a-color">粉丝</a></dt>
                        <dd><span class="count">15</span></dd>
                    </dl>
                    <dl class="text-center">
                        <dt><a href="#" class="a-color">喜欢</a></dt>
                        <dd><span class="count">20</span></dd>
                    </dl>
                    <dl class="text-center">
                        <dt><a href="#" class="a-color">点赞</a></dt>
                        <dd><span class="count">16</span></dd>
                    </dl>
                </div>
            </li>
            {% for sidebar in sidebars %}
                <li class="list-group-item area" id="pro_cate{{ cate.id }}">
                    <h3 class="aside-title">{{ sidebar.title }}</h3>
                    <div class="aside-content">{{ sidebar.content_html }}</div>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

web_blog/themes/default/templates/blog/detail.html
{% extends "blog/base.html" %}
{% load static %}
{% load block %}
{% block title %}{{ post.title }}{% endblock %}
{% block extra_head %}
    <link rel="stylesheet" href="{% static 'default/css/highlight/dark.css' %}">
    <link rel="stylesheet" href="{% static 'default/css/blog.css' %}">
{% endblock %}
{% block main %}
<div class="col-md-8 post-item">
    <ul class="list-group">
        <li class="list-group-item" style="margin-bottom: 5px">
            <ol class="breadcrumb" style="margin: 0px">
                <li><a href="{% url 'post:post-list' auth  %}">Home</a></li>
                <li><a href="{% url 'post:category-list' auth post.category.id %}">{{ post.category.name }}</a></li>
                <li class="active">{{ post.title }}</li>
            </ol>
        </li>
        <li class="list-group-item">
            <h1>{{ post.title }}</h1>
            <div class="article-info">
                <span>{{ post.created_time }}</span>
                <a href="{% url 'post:post-list' post.owner.userinfo.name %}" class="follow-name">{{ post.owner.userinfo.name }}</a>
                <span>阅读数 {{ post.uv }}</span>
            </div>
        </li>
        <li class="list-group-item">
            <article>
                {{ post.content_html|safe }}
            </article>
        </li>
        {% comment_block post.id %}
    </ul>
</div>
{% endblock %}
{% block extra_main %}
    <div class="col-md-1">
        {% snap_block snap post.id %}
    </div>
{% endblock %}
{% block extra_script %}
    <script src="{% static 'default/js/highlight.pack.js' %}"></script>
    <script>hljs.initHighlightingOnLoad();</script>
    <script src="{% static 'default/js/detail.js' %}"></script>
{% endblock %}

web_blog/themes/default/templates/blog/list.html
{% extends "blog/base.html" %}
{% block title %}{{ auth }}{% endblock %}
{% block main %}
<div class="col-md-8 post-item">
    <ul class="list-group">
        <li class="list-group-item" style="margin-bottom: 5px">
            <ol class="breadcrumb" style="margin: 0px">
                <li><a href="{% url 'post:post-list' auth  %}">Home</a></li>
                {% if category %}
                    <li class="active">{{ category.name }}</li>
                {% endif %}
            </ol>
        </li>
        {% for post in post_list %}
            <li class="list-group-item article">
                <h4><p><a href="{% url 'post:post-detail' post.owner.userinfo.name post.id %}"class="a-color">{{ post.title }}</a></p></h4>
                <p>{{ post.desc }}</p>
                <p>{{ post.created_time }}</p>
                <p>分类：{{ post.category.name }}</p>
                <p>阅读量：{{ post.uv }}</p>
            </li>
        {% endfor %}
        {% if page_obj %}
            <li class="list-group-item text-center" style="margin-top: 5px">
            <nav aria-label="Page navigation" style="height: 34px">
            <ul class="pagination" style="margin: 0px">
            {% if page_obj.has_previous %}
                <li>
                <a href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
                </li>
            {% endif %}
                <li><a href="#">Page{{ page_obj.number }} of {{ paginator.num_pages }}</a></li>
            {% if page_obj.has_next %}
                <li>
                <a href="?page={{ page_obj.next_page_number }}"  aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
                </li>
            {% endif %}
            </ul>
            </nav>
            </li>
        {% endif %}
    </ul>
</div>
{% endblock %}
{% block extra_main %}
    <div class="col-md-1">
        <ul class="list-group">
            <li class="list-group-item">
            每日推荐
            </li>
        </ul>
        </div>
{% endblock %}